# Generated by Django 6.0.3 on 2026-03-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_vendor'),
        ('vendors', '0002_remove_vendor_user_vendorprofile_vendorpayout_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vendor',
        ),
    ]
