# Generated by Django 6.0.3 on 2026-03-27 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_delete_vendor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendortransaction',
            old_name='amount',
            new_name='net_amount',
        ),
    ]
