# Generated by Django 6.0.3 on 2026-03-27 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('vendors', '0002_remove_vendor_user_vendorprofile_vendorpayout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendors.vendorprofile'),
        ),
    ]
